# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data

```{r echo=TRUE}
setwd("E:/Data/Coursera/Reproducible Research/week2/RepData_PeerAssessment1")

activity <- read.csv("activity.csv")
library('ggplot2')

# stepCounts <- aggregate(activity$steps, list(activity$date), sum)
# colnames(stepCounts) <- c("date", "steps")

# change to S3 method for forumula rather than class data.frame

stepCounts <- aggregate(steps ~ date, data = activity, sum)

qplot(date, steps, data=stepCounts, geom="histogram")

```

## What is mean total number of steps taken per day?

```{r echo=TRUE}
qplot(date, steps, data=stepCounts, geom="histogram")

mean(stepCounts$steps, na.rm = TRUE)
median(stepCounts$steps, na.rm = TRUE)

```


## What is the average daily activity pattern?

```{r echo=TRUE}
intervalMean <- aggregate(steps ~ interval, data = activity, mean)

qplot(interval, steps, data=intervalMean, geom="line")

# what is the interval, on average across all days, that contains the max number of steps
intervalMean[intervalMean$steps==max(intervalMean$steps),]


```


## Imputing missing values


```{r echo=TRUE}
# calculuate missing values



```


## Are there differences in activity patterns between weekdays and weekends?
